[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

actix-web = "^3.0"

actix-web-static-files = "3.0.5"


[build-dependencies]

actix-web-static-files = "3.0.5"